import type { NextPage } from "next";
import Head from "next/head";
import Redeem from "../components/Redeem";
import { Fragment } from "react";

const App: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>JustArt*</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Redeem />
    </Fragment>
  );
};

export default App;
